POST http://localhost:8080/api/v1/attach/upload
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkwNDE4NzksImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjkxMjgyNzksImlzcyI6IlN0YWRpdW0ifQ.ThXTvsKgGF93B8AUCfmYpTu5fxytmCafhboKFTHx5lj3zuIlSbLHHzj5j6t3lj9ZG3LFtdDLG0dBW6y99iX7BQ
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="lacetti.jpeg"

< C:\Users\Urinov Shokirjon\Desktop\rasmlar\lacetti.jpeg


###
GET http://localhost:8080/api/v1/attach/open/952965d7-fdf7-4434-8df9-6fbf0fee922d.jpg
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg1NTI4NTQsImlkIjoiYmM2Y2ZiYzEtMTU3Yy00ODRjLTlkNzgtN2EwZTBlNWI5YmI3IiwidXNlcm5hbWUiOiIrOTk4OTQxNzg1MTUwIiwicm9sZSI6IlJPTEVfVVNFUiIsInJlZnJlc2hUb2tlbiI6ZmFsc2UsImV4cCI6MTcyODYzOTI1NSwiaXNzIjoiU3RhZGl1bSJ9.q1NCAaBeyGOADuyY3FAZH40IgXgfdw4Xsmvtn1Fo7OIrgmZe6yqpOeAQsJ4mTnm-SocEpDWGJmSlT_s7FSGUWg
