### Order create
POST http://localhost:8080/api/v1/orders
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkwNzM5ODIsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjkxNjAzODIsImlzcyI6IlN0YWRpdW0ifQ.RLNFLntmU3HcsEKt5klNyS1C3BV-pZ_ZKT4CdNSWT_yRcXrSD4s8Q6yLjlCgAdZSqJ5UZwv-8mKMgaX59Sih1Q
Content-Type: application/json

{
  "productCountList": [
    {
      "productId": 1,
      "productsCount": 1
    },
    {
      "productId": 2,
      "productsCount": 2
    },
    {
      "productId": 5,
      "productsCount": 2
    },
    {
      "productId": 6,
      "productsCount": 2
    }

  ]
}

###
GET http://localhost:8080/api/v1/orders/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkwNzM5ODIsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjkxNjAzODIsImlzcyI6IlN0YWRpdW0ifQ.RLNFLntmU3HcsEKt5klNyS1C3BV-pZ_ZKT4CdNSWT_yRcXrSD4s8Q6yLjlCgAdZSqJ5UZwv-8mKMgaX59Sih1Q


###
GET http://localhost:8080/api/v1/orders
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkwNzM5ODIsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjkxNjAzODIsImlzcyI6IlN0YWRpdW0ifQ.RLNFLntmU3HcsEKt5klNyS1C3BV-pZ_ZKT4CdNSWT_yRcXrSD4s8Q6yLjlCgAdZSqJ5UZwv-8mKMgaX59Sih1Q
Content-Type: application/json

{
  "status": "CHECKING"
}

### Order delete
DELETE http://localhost:8080/api/v1/orders/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkwNzM5ODIsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjkxNjAzODIsImlzcyI6IlN0YWRpdW0ifQ.RLNFLntmU3HcsEKt5klNyS1C3BV-pZ_ZKT4CdNSWT_yRcXrSD4s8Q6yLjlCgAdZSqJ5UZwv-8mKMgaX59Sih1Q
